version: '2'
services:
  base:
    build: .
    image: app:base
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
     - "3000:3000"
    volumes:
     - .:/usr/src/app
  doc:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: yard server -b '0.0.0.0'
    volumes:
      - .:/usr/src/app
    ports:
      - "8808:8808"